### ISSUE TITLE
Directions on how to use the service 

### ISSUE THREAD

**Issue by lmcarter621** [lmcarter621/boricua_registry#9]
Currently there is just a fun message on the index page.  There are two options, redirect `found_people` to the index and create an instructions page or leave `found_people` and put the instructions on the index with a button to find people.

**Comment by mrpasquini** [comment]
Added instructions and links: https://github.com/lmcarter621/boricua_registry/commit/4467e7ab4da4792e3f6e28f35bcaf31b685f74f6
